name: Build Radarr with PR #9815

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-alpine  # Alpine-based .NET 6 image

    steps:
      - name: Checkout Your Fork
        uses: actions/checkout@v4
        with:
          repository: ncsufan8628/radarr
          token: ${{ secrets.PA_TOKEN }}
          fetch-depth: 0

      - name: Set Git Identity & Fix Ownership Issue
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /__w/radarr/radarr  # Fix ownership issue

      - name: Add Radarr Upstream
        run: |
          git remote add upstream https://x-access-token:${{ secrets.PA_TOKEN }}@github.com/Radarr/Radarr.git
          git fetch upstream

      - name: Sync with Latest Radarr Master
        run: |
          git fetch --all
          git checkout -B master origin/master
          git merge --ff-only upstream/master || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Merge Fix Branch (PR #9815)
        run: |
          git fetch upstream fix/9815-swap-determiner-on-movietitle:fix-9815
          git checkout master
          git merge fix-9815 --no-edit || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Restore NuGet Packages
        run: dotnet restore src/Radarr.sln

      - name: Build Radarr
        run: dotnet publish src/Radarr.sln --configuration Release --framework net6.0 --output ./output

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Radarr-Build
          path: ./output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          files: ./output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
