name: Build Radarr for Unraid

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Uses Ubuntu, but we run Alpine inside Docker

    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-alpine  # Alpine-based .NET 6 image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache nodejs yarn curl git bash icu-libs

      - name: Install .NET dependencies
        run: |
          apk add --no-cache libgcc libstdc++ krb5-libs zlib

      - name: Build Radarr
        run: |
          chmod +x build.sh
          ./build.sh --backend --frontend --packages -r linux-musl-x64 -f net6.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: radarr-build
          path: _
