name: Build Radarr with PR #9815

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Sync with Latest Radarr Master
        run: |
          git remote add upstream https://github.com/Radarr/Radarr.git || true
          git fetch upstream
          git checkout -B master origin/master
          git merge --ff-only upstream/master || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Merge Fix Branch (PR #9815)
        run: |
          git fetch upstream pull/9815/head:fix-9815
          git checkout master
          git merge fix-9815 --no-edit || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y dotnet-sdk-6.0

      - name: Restore NuGet Packages
        run: dotnet restore src/Radarr.sln

      - name: Build Radarr
        run: dotnet publish src/Radarr.sln --configuration Release --framework net6.0 --output ./output

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Radarr-Build
          path: ./output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          files: ./output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
