name: Radarr Unraid Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: alpine-latest  # Use Alpine runner instead of Ubuntu

    steps:
      - name: Install Dependencies
        run: |
          apk add --no-cache bash curl git nodejs npm dotnet8-sdk icu-libs
          npm install -g yarn

      - name: Clone Radarr Repository
        run: |
          git clone --recursive https://github.com/ncsufan8628/radarr.git
          cd radarr
          git checkout main  # Adjust branch if needed

      - name: Run Backend Build
        run: |
          cd radarr
          ./build.sh --backend -r linux-musl-x64 -f net8.0

      - name: Verify Build Output
        run: |
          cd radarr
          if [ -d "_output/net8.0/linux-musl-x64/publish" ]; then
            echo "Build completed successfully!"
            ls -l _output/net8.0/linux-musl-x64/publish
          else
            echo "Error: Build output not found!" && exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: radarr-build
          path: radarr/_output/net8.0/linux-musl-x64/publish/
