name: Build and Release Radarr

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ncsufan8628/radarr
          token: ${{ secrets.PA_TOKEN }}
          fetch-depth: 0
          submodules: recursive  # Ensures submodules are fetched

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0 jq musl-dev

      - name: Build Radarr
        run: |
          chmod +x build.sh
          ./build.sh --target=linux-musl-x64 > build_output.log 2>&1 || {
            echo "❌ Build failed! Dumping logs:"
            cat build_output.log
            exit 1
          }

      - name: Archive Build Artifacts
        run: |
          tar -czvf radarr-linux-musl-x64.tar.gz -C $OUTPUT_PATH .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: radarr-linux-musl-x64
          path: radarr-linux-musl-x64.tar.gz

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: radarr-linux-musl-x64.tar.gz
          token: ${{ secrets.PA_TOKEN }}
          tag_name: "nightly-${{ github.run_id }}"
          name: "Nightly Build ${{ github.run_id }}"
          body: "Automated nightly build of Radarr."
          draft: false
          prerelease: true
