name: Sync, Merge PR, Build, and Release Radarr

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Change to alpine if needed

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/Radarr/Radarr.git

      - name: Sync with Latest Radarr Master
        run: |
          git fetch --all
          git checkout -B master origin/master
          git merge --ff-only upstream/master || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Merge Fix Branch (PR #9815)
        run: |
          git fetch https://github.com/tempcvrohch/Radarr.git fix/9815-swap-determiner-on-movietitle
          git merge FETCH_HEAD --no-edit || echo "Merge conflicts detected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Set Up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: dotnet restore src/Radarr.sln

      - name: Build Radarr
        run: |
          mkdir -p _artifacts/linux-musl-x64/net6.0/Radarr
          dotnet publish src/Radarr.sln -c Release -r linux-musl-x64 --self-contained false -o _artifacts/linux-musl-x64/net6.0/Radarr

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Radarr Build #${{ github.run_number }}"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build to Release
        uses: softprops/action-gh-release@v2
        with:
          files: _artifacts/linux-musl-x64/net6.0/Radarr/*
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
